### ISSUE TITLE
How to update the memory in the network?

### ISSUE THREAD

**Issue by NeuZhangQiang** [donggong1/memae-anomaly-detection#17]
The paper said: 
```
During training, the memory `M` is updated through optimization via backpropagation and gradient descent.
```
Does it mean that `M` is the optimized parameters in the network?

Thank you very much for any suggestion.

**Comment by donggong1** [comment]
Yes. You can understand it in this way. In some view, M can be seen as a compression of the prototypical dataset in the normal data.

**Comment by NeuZhangQiang** [comment]
Thank you very much !
