### ISSUE TITLE
image_conv2d_version

### ISSUE THREAD

**Issue by wenzhengzeng** [donggong1/memae-anomaly-detection#19]
Is there a conv2d version that aims to reconstruct images like the experiment on MNIST mentioned in the paper?

**Comment by donggong1** [comment]
Sorry. I do not have time to clarify and clean the other part of the code recently. Please drop me an email. I will try to find time to send you an uncleaned copy for your reference.

**Comment by youngupup** [comment]
@alexzeng1206 Hi,Do you have the code of conv2d version?

**Comment by kanwangshijie** [comment]
Hello, can you send me the code of 2D convolution  or uncleaned copy for image detection, my email is 2718191965@qq.com, thank you

**Comment by kanwangshijie** [comment]
> Sorry. I do not have time to clarify and clean the other part of the code recently. Please drop me an email. I will try to find time to send you an uncleaned copy for your reference.

Hello, can you send me the code of 2D convolution or uncleaned copy for image detection, my email is 2718191965@qq.com, thanks.
